# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Zheyuan(Brian) Zhang
email:
description: >- # this means to ignore newlines until "baseurl:"
  Zheyuan(Brian) Zhang
twitter_username: cozzyde
github_username: cozheyuanzhangde
minimal_mistakes_skin: default
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   :
  avatar : "/assets/images/robotme.jpg"
  bio    :
  location  : "Amherst, MA"
  links:
    - label: "zheyuanzhang@umass.edu"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:zheyuanzhang@umass.edu"
    - label: "Website"
      icon: "fas fa-fw fa-link"
      # url: "https://your-website.com"
    - label: "cozzyde"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/cozzyde"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      # url: "https://facebook.com/"
    - label: "cozheyuanzhangde"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/cozheyuanzhangde"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      # url: "https://instagram.com/"

footer:
  links:
    - label: "cozzyde"
      icon: "fab fa-fw fa-twitter-square"
      url: https://twitter.com/cozzyde
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      # url:
    - label: "cozheyuanzhangde"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/cozheyuanzhangde"
    - label: "GitLab"
      icon: "fab fa-fw fa-gitlab"
      # url:
    - label: "Bitbucket"
      icon: "fab fa-fw fa-bitbucket"
      # url:
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      # url:

webmaster_verifications:
  google: _w-JPsbKKLeqMqTroyAJLmdtVH1_9xF46o9yjQopgqg

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-GCJZ9EV9M8"
    anonymize_ip: false
